services:
  - docker

before_install:
  - docker pull ounishatem/docker-rpi-emu


script:
  - docker run -d -name docker-rpi-emu ounishatem/docker-rpi-emu /bin/bash -c './run.sh'
  - docker logs -f docker-rpi-emu