services:
  - docker

before_install:
  - docker pull ounishatem/docker-rpi-emu


script:
  - docker run -d -P --name docker-rpi-emu -v "$TRAVIS_BUILD_DIR":/home/pi ounishatem/docker-rpi-emu /bin/bash -c '/home/pi/run.sh'
  - docker logs -f docker-rpi-emu