image: ryankurte/docker-rpi-emu

definitions:
  steps:
    - step: &raspbian-setup
        name: Raspbian Setup
        script:
          - bash raspbiansetup.sh
        services:
          - docker
        caches:
          - docker
    - step: &install-rgb
          name: Install RGB
          script:
            - bash install_rgb.sh
          services:
            - docker
          caches:
            - docker

pipelines:
  default:
    - step: *raspbian-setup
    - step: *install-rgb