
image: ounishatem/docker-rpi-emu

definitions:
  steps:
    - step: &raspbian-setup
        name: Raspbian Setup
        script:
          - export OLT_TENANT=Hatemorg
          - export OLT_RASPBERRY_DEVICE=White
          - bash raspbiansetup.sh
        services:
          - docker
        caches:
          - docker
    - step: &install-camera
          name: Install Camera
          script:
            - export OLT_TENANT=Hatemorg
            - export OLT_CAMERA_DEVICE=Camera
            - bash install_camera.sh
          services:
            - docker
          caches:
            - docker
    - step: &install-distance
          name: Install Distance
          script:
            - export OLT_TENANT=Hatemorg
            - export OLT_DISTANCE_DEVICE=Distance
            - bash install_distance.sh
          services:
            - docker
          caches:
            - docker
    - step: &install-fan
          name: Install Fan
          script:
            - bash install_fan.sh
          services:
            - docker
          caches:
            - docker
    - step: &install-link
          name: Install Link
          script:
            - export OLT_TOKEN=SomeToken
            - export OLT_DISTANCE_DEVICE=41d8342f-5a99-4ebe-a6cb-6a7553c9eb62
            - export OLT_SCREEN_DEVICE=fcc8a4ec-bec2-439b-862c-1c930ca8d0b1
            - bash install_link.sh
          services:
            - docker
          caches:
            - docker
    - step: &install-presence
          name: Install Presence
          script:
            - export OLT_TENANT=Hatemorg
            - export OLT_PRESENCE_DEVICE=Presence
            - bash install_presence.sh
          services:
            - docker
          caches:
            - docker
    - step: &install-rgb
          name: Install RGB
          script:
            - export OLT_TENANT=Hatemorg
            - export OLT_RGB_DEVICE=Rgb
            - export OLT_RGB_DEVICE_ID=SomeId
            - bash install_rgb.sh
          services:
            - docker
          caches:
            - docker
    - step: &install-screen
          name: Install Screen
          script:
            - export OLT_TENANT=Hatemorg
            - export OLT_SCREEN_DEVICE=Screen
            - export OLT_SCREEN_DEVICE_ID=fcc8a4ec-bec2-439b-862c-1c930ca8d0b1
            - bash install_screen.sh
          services:
            - docker
          caches:
            - docker

pipelines:
  default:
    - step: *raspbian-setup
    - step: *install-camera
    - step: *install-distance
    - step: *install-fan
    - step: *install-presence
    - step: *install-rgb
    - step: *install-screen
    - step: *install-link